spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fts
    username: postgres
    password: password
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    root: info
    org:
      springframework: info
      hibernate: info
    com:
      anastasiakassari:
        financialtransactionservice: debug

